project:
  type: website
  output-dir: docs
  
website:
  title: "futureverse"
  repo-url: https://github.com/astamm/futureverse/
  repo-actions: [edit, source, issue]
  page-footer: 
    background: light
    left: Copyright 2024, Aymeric Stamm
    right: This website is built with [Quarto](https://quarto.org/)
  navbar:
    logo: logo-futureverse.png
    left:
      - text: "Part 1"
        menu:
          - text: "Slides"
            url:  https://docs.google.com/presentation/d/1P3gHm26OPbN4Ftnr_QHw_FmHgDVtOWcC64yIWx63KtY/edit?usp=sharing
          - text: "Lab"
            href: lab/lab1.qmd
      - text: "Part 2"
        menu:
          - text: "Slides"
            url:  https://docs.google.com/presentation/d/1RN1ru9-HoOKsIjORZECFmDvzWbpVn0ZsyQDl3X37fbU/edit?usp=sharing
          - text: "Lab"
            href: lab/lab2.qmd
      - text: "Case Study"
        menu:
          - text: "Instructions"
            href: casestudy/hausdorff_dist.qmd
          - text: "Solutions"
            href: casestudy/hausdorff_dist_solutions.qmd
      - text: "FAQ"
        href: faq/futureverse-faq.qmd
    right:
      - icon: github
        href: https://github.com/astamm/futureverse/
        
  search: 
    location: navbar
    type: overlay
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
