project:
  type: website
  output-dir: docs
  
website:
  title: "Futureverse - ANF High Performance Computing with R"
  navbar:
    left:
      - text: "Part 1"
        menu:
          - text: "Slides Part 1 (online)"
            url:  https://docs.google.com/presentation/d/1P3gHm26OPbN4Ftnr_QHw_FmHgDVtOWcC64yIWx63KtY/edit?usp=share_link
          - text: "Lab 1"
            href: lab1.qmd
      - text: "Part 2"
        menu:
          - text: "Slides Part 2 (online)"
            url:  https://docs.google.com/presentation/d/1RN1ru9-HoOKsIjORZECFmDvzWbpVn0ZsyQDl3X37fbU/edit?usp=share_link
          - text: "Lab 2"
            href: lab2.qmd
        
  search: 
    location: navbar
    type: overlay
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
